name: store
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.5.0
  shared_preferences: ^2.5.3
  remixicon: ^1.4.1
  flutter_screenutil: ^5.9.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
    - assets/fonts/



  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700 
flutter_native_splash:
  color: "#514eb7" 
  image: assets/images/logo.png 
  android: true
  ios: true
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

 
